# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\'\n\x04Note\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eUserValidation\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32\x92\x01\n\x07Greeter\x12\x36\n\x0cValidateUser\x12\x0e.chat.UserName\x1a\x14.chat.UserValidation\"\x00\x12*\n\nChatStream\x12\x0e.chat.UserName\x1a\n.chat.Note0\x01\x12#\n\x08SendNote\x12\n.chat.Note\x1a\x0b.chat.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTE._serialized_start=20
  _NOTE._serialized_end=59
  _EMPTY._serialized_start=61
  _EMPTY._serialized_end=68
  _USERNAME._serialized_start=70
  _USERNAME._serialized_end=94
  _USERVALIDATION._serialized_start=96
  _USERVALIDATION._serialized_end=129
  _GREETER._serialized_start=132
  _GREETER._serialized_end=278
# @@protoc_insertion_point(module_scope)
